[package]
edition = "2021"
name = "bload_oath"
version = "0.1.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true

[features]
default = ["debug", "parallel"]
parallel = ["rayon"]
debug = []

[dependencies]
bo_ecs = { path = "bo_ecs/" }
bo_map = { path = "bo_map/" }
bo_utils = { path = "bo_utils/" }

bracket-lib = { version = "^0.8.1", features = ["serde"] }
rayon = { version = "^1.5.3", optional = true }
specs = { version = "^0.18.0", default_features = false, features = [
  "parallel",
  "derive",
] }

lazy_static = "1.4.0"
parking_lot = { version = "^0.12.1", features = ["nightly"] }
bitvec = "^1.0.1"

[build-dependencies]
embed-resource = "1.7.3"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

members = ["bo_utils", "bo_ecs", "bo_map"]
