[package]
name = "bo_utils"
version = "0.1.0"
authors = ["Jacob LeCoq <lecoqjacob@gmail.com>"]
edition = "2021"

[dependencies]
bracket-terminal = "^0.8.5"
bracket-random = "^0.8.2"
lazy_static = "^1.4.0"
parking_lot = "^0.12.1"
